import { ChangeDetectionStrategy, Component, ElementRef, effect, input, output, viewChild } from '@angular/core';
@Component({selector:'cp-dialog',standalone:true,template:`@if(open()){<div class="backdrop" (mousedown)="backdropClick($event)"><section #dialog class="dialog" role="dialog" aria-modal="true" [attr.aria-labelledby]="titleId()" tabindex="-1"><header><div><h2 [id]="titleId()">{{title()}}</h2>@if(description()){<p>{{description()}}</p>}</div><button type="button" aria-label="Close dialog" (click)="closed.emit()">×</button></header><div class="body"><ng-content /></div><footer><ng-content select="[cpDialogActions]" /></footer></section></div>}`,
styles:[`.backdrop{position:fixed;inset:0;z-index:var(--cp-z-modal);display:grid;place-items:center;padding:var(--cp-space-5);background:var(--cp-scrim);backdrop-filter:blur(8px)}.dialog{width:min(38rem,100%);max-height:90vh;overflow:auto;padding:var(--cp-space-6);border:1px solid var(--cp-border);border-radius:var(--cp-radius-xl);background:var(--cp-surface);box-shadow:var(--cp-shadow-lg)}header{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--cp-space-4)}h2{margin:0;font:400 1.75rem/1.2 var(--cp-font-display)}p{margin:.3rem 0 0;color:var(--cp-text-muted)}header button{width:2.5rem;height:2.5rem;border:0;border-radius:var(--cp-radius-md);background:var(--cp-surface-subtle);color:var(--cp-text);cursor:pointer;font-size:1.3rem}.body{margin-top:var(--cp-space-5)}footer{display:flex;justify-content:flex-end;gap:var(--cp-space-2);margin-top:var(--cp-space-5)}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class CpDialogComponent{readonly open=input(false);readonly title=input.required<string>();readonly description=input('');readonly titleId=input('cp-dialog-title');readonly closed=output<void>();private readonly dialog=viewChild<ElementRef<HTMLElement>>('dialog');constructor(){
  // A one-shot afterNextRender only ever focuses the dialog the first time this component happens to
  // render with open()=true; a dialog left mounted with [open]="someSignal()" (the common consumer
  // pattern, starting closed) never gets focus on any later open. An effect re-fires on every
  // transition, once the @if(open()) branch has actually created #dialog for viewChild to see.
  effect(()=>{if(this.open())this.dialog()?.nativeElement.focus();});
}backdropClick(event:MouseEvent){if(event.target===event.currentTarget)this.closed.emit();}}
