namespace CreatorPantry.Domain.Modules.Media.Managers;

/// <summary>
/// Where an asset's bytes came from (media.md). Stored as its number; append, never renumber.
/// </summary>
/// <remarks>
/// A fact about provenance rather than about format or use. It is set when an asset is created and does
/// not change: a creator who uploads a photograph and later adds a generated variant as a new version has
/// an <see cref="Original"/> asset whose second version records its own source, not an asset that became
/// something else.
/// </remarks>
public enum MediaAssetKind
{
    /// <summary>Not declared. Never valid on a stored row — the check constraint refuses it.</summary>
    Unspecified = 0,

    /// <summary>A creator upload. The default, and the only kind whose bytes nobody else has seen.</summary>
    Original = 1,

    /// <summary>Obtained through an integration, with its source and rights recorded.</summary>
    Imported = 2,

    /// <summary>A crop, resize or conversion of another asset.</summary>
    Derived = 3,

    /// <summary>Generated by a model, with the provenance the generating version records.</summary>
    AiGenerated = 4,
}

/// <summary>Where one version's bytes came from. Stored as its number; append, never renumber.</summary>
/// <remarks>
/// Per version rather than per asset, because that is where bytes live. An asset's second version may
/// arrive by a different route from its first, and a download has to be able to say which.
/// </remarks>
public enum MediaAssetVersionSource
{
    Unspecified = 0,

    /// <summary>Uploaded by a creator, as it arrived.</summary>
    Upload = 1,

    /// <summary>
    /// Copied from a staged generated image the creator kept.
    /// </summary>
    /// <remarks>
    /// The version records which one in <c>SourceGeneratedImageId</c>, so an asset can always say what
    /// made it even after retention has removed the staged copy's bytes (12.8).
    /// </remarks>
    GeneratedImage = 2,
}
